# Generated by Django 3.2.7 on 2023-07-14 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_salud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enfermedad',
            name='id_enfermedad',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
