# Generated by Django 3.2.7 on 2023-07-14 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_salud', '0003_alter_etapa_id_etapa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sintomas',
            fields=[
                ('id_sintomas', models.AutoField(primary_key=True, serialize=False)),
                ('sintoma_detalle', models.TextField()),
                ('cuidados', models.TextField()),
                ('consideraciones', models.TextField()),
                ('obligatoriedad', models.CharField(max_length=50)),
                ('enfermedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_salud.enfermedad')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_salud.etapa')),
            ],
        ),
    ]
