# Generated by Django 3.2.7 on 2023-07-14 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_salud', '0004_sintomas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sintomas',
            name='obligatoriedad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
