version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: ipp_salud
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234

  web:
    build: .
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - .:/app